{
  imports = [
    ./base
    ./host.nix
    ./boot/zfs.nix
    ./disko
    ./networking
    ./networking/static.nix
    ./networking/wireless.nix
    ./networking/wifi-profiles.nix
    ./desktop
    ./services/openssh.nix
    ./services/xrdp.nix
    ./services/incus.nix
    ./virtualization/vfio.nix
    ./power/prevent-sleep.nix
    ./secrets.nix
    ./home-manager.nix
    ./system-info
  ];
}
